### ISSUE TITLE
[v4.0] Can't split documentation into separate YAML files. 

### ISSUE THREAD

**Issue by LukSky24** [nelmio/NelmioApiDocBundle#1731] opened 2020-10-16 08:03 UTC
Hey!
I am using version 4.0 of this bundle and I want to split my documentation into separate yaml files to get clean repository and don't have one file with more that 500 lines of code. 
But when i am using $ref field i get error and Symfony (v5.1) don't seems to work with this configuration.
Below is my **/var/www/testapp/config/packages/nelmio_api_doc.yaml** config:
```yaml
nelmio_api_doc:
    documentation:
        openapi: "3.0.0"
        servers:
            -   url: http://localhost:8080
        info:
            title: Test App
            description: Application for testing
            version: 1.0.0
        tags:
            -   name: Auth
                description: Authorization tools
        components:
            securitySchemes:
                Bearer:
                    description: "Paste a Bearer Token that you get from login command (/api/frontend/auth/login)."
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            responses:
                $ref: "./open_api/responses.yaml"
        security:
            -   bearerAuth: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/frontend
```
Code form file **var/www/testapp/config/packages/open_api/responses.yaml**:
```yaml
todo:
  description: 'This API call has no documentated response (yet)'
```
and when I refresh my api/doc page I get:
`User Notice: Missing required field "description" for @OA\Response() in \Nelmio\ApiDocBundle\ApiDocGenerator->generate() in /var/www/html/vendor/nelmio/api-doc-bundle/ApiDocGenerator.php on line 82`

If i don't use external files and paste code from response.yaml to nelmio_api_doc.yaml everything works fine.
Could you help me and tell me what I am doing wrong? Or maybe i must do something else.
Thanks.

**Comment by GuilhemN** [comment] 2020-10-19 16:33
I don't think you can refer to other files for the `responses` field.
You can use `$ref` for specific responses/parameters/etc but not for all of them. 

Besides, please note that such an usage of `$ref` (if it was under a path supporting it of course) will be forwarded to the client that will then have to fetch the file `./open_api/responses.yaml`, and hence this file would need to be publicly available.

If you want to merge two OpenApi documentations from you server, please have a look at https://github.com/nelmio/NelmioApiDocBundle/issues/1654.

**Comment by hubertnnn** [comment] 2020-10-27 07:51
I got the same issue. 
It seems like Symfony is failing to merge the config files and you end up with only one of them being loaded.

As a workaround I used multiple external documentations (one per file loaded) and that works like a charm, though require a bit of extra work.

In your bundle extension:
```
    public function load(array $configs, ContainerBuilder $container)
    {
        $loader = new YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.yaml');

        // Load documentation
        $documentation = Yaml::parseFile(__DIR__.'/../Resources/config/documentation.yaml');
        $container->getDefinition('nelmio_api_doc.describers.config.acme_pagination_bundle')->setArgument(0, $documentation);
    }
```

In services.yaml
```
  nelmio_api_doc.describers.config.acme_pagination_bundle:
    class: Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
    tags: [{ name: nelmio_api_doc.describer, priority: 1000 }]
```

**Comment by chrisguitarguy** [comment] 2022-05-16 11:36
Going to close this as a duplicate of #1666

**Closed by chrisguitarguy** 2022-05-16 11:36 UTC
