### ISSUE TITLE
[Question] How to add custom "Definitions" to avoid code duplication?

### ISSUE THREAD

**Issue by timonf** [nelmio/NelmioApiDocBundle#1206] opened 2018-01-25 13:51 UTC
Hi there :)

I have a small question: How can I put custom definitions, so that I can reuse them as reference? I wan't to avoid duplicate code according to [this section](https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#dont-repeat-yourself).

See the Definition annotations from Swagger PHP:
- https://github.com/zircote/swagger-php/blob/master/Examples/dynamic-reference/api-spec.php
- https://github.com/zircote/swagger-php/blob/master/Examples/using-refs/api-spec.php

I want to use a custom definition like "product_status". But in Nelmio where I have to define them?

```php
/**
 * @SWG\Definition(
 *   definition="product_status",
 *   type="string",
 *   description="The status of a product",
 *   enum={"available", "discontinued"},
 *   default="available"
 * )
 */
```

In class, in configuration, in JSON, in separate PHP file…? I don't know :(

I tried to put it everywhere, but I got always the same error message in UI:

```
Errors

Resolver error at definitions.ProductFilter.properties.productStatuses.items.$ref
Could not resolve reference: #/definitions/product_status
```

Using this:

```php
    /**
     * @var array|null
     * @SWG\Property(type="array", @SWG\Items(ref="#/definitions/product_status"))
     */
    public $productStatuses;
```

or using this Code:

```
    /**
     * @var string|null
     * @ApiDoc\Property(ref="#/definitions/product_status")
     */
    public $productStatus;
```

Regards
Timon

**Comment by GuilhemN** [comment] 2018-01-25 13:53
The `@Definition` annotation is replaced by `@Model` when using this bundle ;) See https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#use-models.

**Comment by timonf** [comment] 2018-01-25 14:08
Thanks, @GuilhemN! :)

So I have to create a simple value object called ProductStatus? And where should I define the possible enum values then?

And: I want to use them on a attribute on another class. Not directly as response or parameter. Does this work?

**Comment by GuilhemN** [comment] 2018-01-25 14:12
> So I have to create a simple value object called ProductStatus?

Yes, or you can put it in your config (see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#using-the-bundle).

>And where should I define the possible enum values then?

``@SWG\Parameter::$enum`` will be supported in 3.1. Or it is already when putting a definition in your config.

> And: I want to use them on a attribute on another class. Not directly as response or parameter. Does this work?

If that's an object, just type hint your attribute. Otherwise you'll be able to use ``@SWG\Parameter::$ref`` in 3.1.

**Comment by GuilhemN** [comment] 2018-01-27 11:55
Closing as I guess the issue is fixed.

**Closed by GuilhemN** 2018-01-27 11:55 UTC
