### ISSUE TITLE
OpenApi\Analysis::getSchemaForSource(): Argument #1 ($fqdn) must be of type string, array given,

### ISSUE THREAD

**Issue by jdechavanne** [nelmio/NelmioApiDocBundle#2152] opened 2023-11-18 21:34 UTC
Hi there, 
I have a simple symfony 6.3 project with php 8.2  Api platform 3.2 and Nelmio api doc. 
Then i generate a simple Post entity with title and description but when i want to access nelmio doc, i have the following error. 

`OpenApi\Analysis::getSchemaForSource(): Argument #1 ($fqdn) must be of type string, array given,`

After investigate, i've found that if i describe manually my operation from api platform, it works well : 

```php
#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ApiResource(
    new Get(),
    new Post(),
    new Put(),
    new Patch(),
    new Delete(),
)]
class PostArticle
```

But then here we go, i set the `new GetCollection()` attribute, and the error appear again :/ 

I can't figure out the problem :'( 

Here is my require part in composer.json file 

```json
"require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/core": "^3.2",
        "doctrine/doctrine-bundle": "^2.11",
        "doctrine/doctrine-migrations-bundle": "^3.3",
        "doctrine/orm": "^2.16",
        "nelmio/api-doc-bundle": "^4.12",
        "nelmio/cors-bundle": "^2.3",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.24",
        "symfony/asset": "6.3.*",
        "symfony/console": "6.3.*",
        "symfony/dotenv": "6.3.*",
        "symfony/expression-language": "6.3.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.3.*",
        "symfony/property-access": "6.3.*",
        "symfony/property-info": "6.3.*",
        "symfony/runtime": "6.3.*",
        "symfony/security-bundle": "6.3.*",
        "symfony/serializer": "6.3.*",
        "symfony/translation": "6.3.*",
        "symfony/twig-bundle": "6.3.*",
        "symfony/validator": "6.3.*",
        "symfony/yaml": "6.3.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
```

**Comment by xammmue** [comment] 2023-11-20 17:07
I got the same issue when upgrading from Api platform 2.7 to ApiPlatform 3.2. Looking forward to finding a solution here.
```
TypeError : OpenApi\Analysis::getSchemaForSource(): Argument #1 ($fqdn) must be of type string, array given, called in /var/www/symfony/vendor/zircote/swagger-php/src/Processors/AugmentSchemas.php on line 106
```

We are using these versions:
```
api-platform/core 3.2.5
nelmio/api-doc-bundle 4.12.0
zircote/swagger-php 4.7.15
```

There is an issue in [zircote/swagger-php](https://github.com/zircote/swagger-php) which got closed as it was deemed as unrelated to their project: https://github.com/zircote/swagger-php/issues/1464

Looking forward to finding a solution here

**Comment by sauls** [comment] 2023-11-22 08:36
This is caused by ApiPlatform integration, mayne we can have this also controlled using configuration like `enable_api_platform`.

So instead in `DependencyInjection/NelmioApiDocExtension.php:170-173`

```php
// ApiPlatform support
if (isset($bundles['ApiPlatformBundle']) && class_exists('ApiPlatform\Documentation\Documentation')) {
    $loader->load('api_platform.xml');
}
```
Would be nice not to force api platform integration

```php
// ApiPlatform support
if ($config['enable_api_platform'] && isset($bundles['ApiPlatformBundle']) && class_exists('ApiPlatform\Documentation\Documentation')) {
    $loader->load('api_platform.xml');
}
```

I know this doesn't fix the problem, but at least having this option we can have separate UIs that work, until the problem is fixed. 

My project use case is that v1 is under nelmio api docs , and we are moving to v2 using api-platform, both docs are rendered separately. So now only v2 renders correctly while v1 gets this exception too...

**Comment by DjordyKoert** [comment] 2023-11-22 13:57
I have a work in progress PR open at [zircote/swagger-php](https://github.com/zircote/swagger-php) https://github.com/zircote/swagger-php/pull/1502. 

This happens because Api platform 3.2 creates documentation according to openapi spec 3.1.0 which allows types to be defined as a string or a list of types. A list of types causes a `TypeError` because that method only accepts `string` as a parameter but an arrar (list of types) is passed instead.

**Comment by jdechavanne** [comment] 2023-11-22 15:20
Thanks @DjordyKoert for you feedback 🙏

**Comment by DjordyKoert** [comment] 2023-11-30 22:41
https://github.com/zircote/swagger-php/pull/1502 has been merged so a simple update of swagger-php on your project should fix the issue :smile:

**Comment by jdechavanne** [comment] 2023-12-03 18:09
Thanks @DjordyKoert 
I have another error now, Warning: Undefined array key "owl:maxCardinality"

But i don't think it's related 🤔

**Closed** 2024-01-02 11:48 UTC
