### ISSUE TITLE
MappingException with indexBy

### ISSUE THREAD

**Issue by nlhommet** [nelmio/NelmioApiDocBundle#1541] opened 2019-08-22 07:57 UTC
I have a MappingException when I use an indexBy annotation.

Example :
```
<?php
...
class Product
{
...
  /**
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Product\Store\Price",
     *     mappedBy="product",
     *     cascade={"all"},
     *     orphanRemoval=true,
     *     indexBy="price_type_id"
     * )
     * @Groups({"productStore:list"})
     * @var Collection
     */
    private $prices;

...
}
```
```
<?php
...
class Price
{
...
   /**
     * @ORM\ManyToOne(
     *     targetEntity="App\Entity\Product\Price\Type"
     * )
     * @ORM\JoinColumn(name="price_type_id",referencedColumnName="id")
     * @Groups("productStore:list")
     * @var Type
     */
    private $type;
...
}
```

With this configuration my REST API return works perfectly but my doc page throw a MappingException
`No mapping found for field 'price_type_id' on class 'App\Entity\Product\Store\Price'.`

If I change the `@indexBy` by `indexBy="type"`, the doc works but not the API return.

Have I misconfigured something?

**Comment by chrisguitarguy** [comment] 2022-04-01 20:58
Goign to close this due to age.

To reopen: need some more details on the `MappingException` (like a stack trace, is it coming from this bundle?) or maybe a reproducer project.

**Closed by chrisguitarguy** 2022-04-01 20:58 UTC
