### ISSUE TITLE
Show error when param requirement is null

### ISSUE THREAD

**Issue by Chrysweel** [nelmio/NelmioApiDocBundle#709] opened 2015-09-14 09:39 UTC
Hello.

I have a url:
>GET /api/users/{username_partial}/search 

If the user call this method without username_partial, I have to show error.
In controller I get username_partial = '{username_partial}'

Now one solution is, in controller to include:
```
if ($username_partial == '{username_partial}'){
 to show error;
}
```

But I think that is a wrong way.. 
What is the correct way to do this?

Thanks in advance!

**Comment by Chrysweel** [comment] 2015-09-15 10:38
Today I saw that other issue reference it ! :_)

https://github.com/nelmio/NelmioApiDocBundle/issues/531

**Comment by willdurand** [comment] 2015-10-27 09:45
duplicate of #531

**Closed** 2015-10-27 09:45 UTC
