### ISSUE TITLE
Error with flex

### ISSUE THREAD

**Issue by szepczynski** [nelmio/NelmioApiDocBundle#1144] opened 2017-12-14 10:23 UTC
NelmioApiDoc has no recipe for flex and does not have routing file in default location.
Installing this bundle by flex cause this error:

```
!!    [Symfony\Component\Config\Exception\FileLoaderLoadException]
!!    Unable to find file "@NelmioApiDocBundle/Resources/config/routing.yml" in @
!!    NelmioApiDocBundle/Resources/config/routing.yml (which is being imported fr
!!    om "/storage/jobsquare/jobsquare-backend/sf/config/routes/nelmio_api_doc.ya
!!    ml"). Make sure the "NelmioApiDocBundle" bundle is correctly registered and
!!     loaded in the application kernel class. If the bundle is registered, make
!!    sure the bundle path "@NelmioApiDocBundle/Resources/config/routing.yml" is
!!    not empty.
!!
!!
!!
!!    [InvalidArgumentException]
!!    Unable to find file "@NelmioApiDocBundle/Resources/config/routing.yml".
```

**Comment by unglud** [comment] 2017-12-15 12:58
https://github.com/symfony/recipes-contrib/pull/207

**Comment by GuilhemN** [comment] 2017-12-17 09:12
Duplicate of https://github.com/nelmio/NelmioApiDocBundle/issues/1143

**Closed by GuilhemN** 2017-12-17 09:12 UTC
