### ISSUE TITLE
Private properties exposure with Symfony 5.2

### ISSUE THREAD

**Issue by javer** [nelmio/NelmioApiDocBundle#1756] opened 2020-12-03 15:19 UTC
After upgrading project from Symfony 5.1 to Symfony 5.2 all private/protected properties and methods in models are exposed as accessible in generated APIDoc.

I don't use JMS Serializer or any other custom serializers, just bundled Symfony Serializer.

See how-to-reproduce project to see it in action: https://github.com/javer/NelmioApiDoc4SF52PrivateExposure

Issue related to these PRs:
* https://github.com/symfony/symfony/pull/37040
* https://github.com/nelmio/NelmioApiDocBundle/pull/1665

Downgrading to Symfony 5.1 fixes this issue.

The only available option to hide private/protected properties is marking each of them with `@Ignore` annotation which also doesn't work at the moment due to the issue https://github.com/symfony/symfony/pull/39299

But we shouldn't have to hide hidden by default (because of protected/private) properties/methods as it works with previous versions of Symfony or with older versions of NelmioApiDocBundle.

**Comment by arjanfrans** [comment] 2020-12-16 15:30
I am having the same problem after upgrading. I have a protected method, which it now tries to classify automatically, which results in an error.

**Comment by GuilhemN** [comment] 2020-12-16 20:54
Thank you for the report and the reproducer @javer!
Your PR https://github.com/symfony/symfony/pull/39299 was merged, and there will be a release in the coming days so I don't think we should add an hack in this bundle just to fix it meanwhile.

**Comment by javer** [comment] 2020-12-16 21:24
@GuilhemN  Unfortunately no, because merged in Symfony patch will not fix the wrong behavior introduced in the recent versions of ApiDocBundle, it will only allow you to make workaround by manually marking EVERY private and protected method in such models (thousands of places in real projects) with `Ignore` annotation, which doesn't sound like something reasonable, because these methods are private and shouldn't be visible outside of the class by definition. So BC break introduced in #1665 won't be fixed in the way as it worked before.

**Comment by GuilhemN** [comment] 2020-12-16 21:48
Oh I see...
But actually that means that the Symfony serializer doesn't ignore these properties, right? So adding them makes your doc more compliant with the actual API don't you think?

> But we shouldn't have to hide hidden by default (because of protected/private) properties/methods as it works with previous versions of Symfony or with older versions of NelmioApiDocBundle.

For me, it was not really intended, there is no way to unhide these properties and adopting the behavior of the actual underlying serializer makes more sense

**Comment by arjanfrans** [comment] 2020-12-16 22:08
The error I am getting is:

```
Property \"App\\RequestObject\\ContactFilterRequestObject::searchableParameters\" is an array, but its items type isn't specified. You can specify that by using the type `string[]` for instance or `@SWG\\Property(type=\"array\", @SWG\\Items(type=\"string\"))`.
```

The code for my protected method looks like this (it actually comes from a trait which I use in my ContactFilterRequestObject class):

```
    /**
     * @param ParameterBag<string, mixed> $parameters
     */
    protected function setSearchableParameters(ParameterBag $parameters): void
    {
        $this->search = QueryParameter::getFilterValue($parameters, 'search');
    }
```

Why does it think that it is an array? 

In my architecture I have objects which basically "convert" the ParameterBag body into an object (in this case `ContactFilterRequestObject`) for validation and generating automated documentation for the request parameters. These objects contain private/protected methods that I use as helpers.

1. It shouldn't classify this method as an array right, it returns void? 2. For my use case here, this is definitely a BC break, I'd have to rewrite the code or annotate all the private/protected methods/properties with `@Ignore`.

**Comment by javer** [comment] 2020-12-16 22:13
@GuilhemN 
> But actually that means that the Symfony serializer doesn't ignore these properties, right? 

No, because Symfony Serializer actually ignores private and protected properties/methods as it should be, see response from serialized and generated documentation in my reproducer readme: https://github.com/javer/NelmioApiDoc4SF52PrivateExposure#how-to-reproduce .

Only `SerializerExtractor` from `PropertyInfo` component returns hidden properties/methods which aren't actually serialized then. So it seems that using `SerializerExtractor` is not the appropriate way to get list of properties/methods which will be serialized, or its results should be post-processed to reject non-visible properties or properties with non-visible accessors.

> So adding them makes your doc more compliant with the actual API don't you think?

Please take a look at the reproducer sample model: https://github.com/javer/NelmioApiDoc4SF52PrivateExposure/blob/master/src/DTO/ResponseDTO.php#L22
Do you really think that we need mark all such private/protected methods (results of which won't be actually serialized, see above explanation) should be marked as Ignored only for generating correct documentation? if yes, why it's not necessary when using JMS Serializer despite the fact that serialization results are the same for both serializers (Symfony and JMS)?

**Comment by GuilhemN** [comment] 2020-12-16 22:25
Ok, thank you for the detailed explanation.

I think there is definitely an issue in the `SerializerExtractor`, but you're right since it may take some time to fix it (if ever) we should do something here.
I have a fix in mind, let me some time to submit it.

**Comment by javer** [comment] 2020-12-17 08:11
@GuilhemN , thank you! I can confirm that it fixes the issue.

**Comment by GuilhemN** [comment] 2020-12-17 08:28
PRs merged! Thanks for the report again :)

**Closed by GuilhemN** 2020-12-17 08:28 UTC

**Comment by javer** [comment] 2020-12-17 14:06
@GuilhemN Could you please make new releases for 3.x and 4.x branches to be able to use these fixes?

**Comment by GuilhemN** [comment] 2020-12-27 18:17
it's released under 3.8.1 and 4.1.1 :)

**Comment by NetBT** [comment] 2024-10-17 10:10
@GuilhemN 
I don't understand why you made this change. The previous code logic had already filtered out the properties that the interface should return using `Groups ` attribute. The properties obtained here through `ReflectionExtractor `are in camelCase format. If the properties configured with Groups are in snake_case format, then the fields that need to be displayed will be omitted here.

**Comment by frsmoray** [comment] 2025-05-27 08:39
Neither do I understand why. Snake case properties are eliminated since the filtering for this issue came in:

![Image](https://github.com/user-attachments/assets/de7eca80-12b6-48dc-9fe0-1d5b50abd104)
