### ISSUE TITLE
Unable to merge @SWG\Get() (Multiple actions under same path)

### ISSUE THREAD

**Issue by mrthehud** [nelmio/NelmioApiDocBundle#1726] opened 2020-10-01 11:32 UTC
I have a controller that has two actions, and which of these actions Symfony executes is determined by a request condition.

If the `override` query parameter is set, then the `getMyActionOverride` action is executed, otherwise `getMyAction` is executed.

This seems to cause raise an `ErrorException` with message "Unable to merge @SWG\Get() in \MyController->getMyAction()"
(That seems to be triggered by logging an E_USER_NOTICE, which I think triggers that exception when in Symfonys `dev` environment):
```
Logger::notice('Unable to merge '.$operation->identity() .' in '.$operation->_context);
```

These actions get merged into a single operation in the swagger, despite having different `operationId`s.

I would expect (by having different operation Ids) for these to generate two separate operations in the swagger. I've tried overriding the `path` property of the Operation, to `/myaction?override=*` and `/myaction`, but that triggers an alternate warning, and thus ErrorException, of:
User Warning: Multiple definitions for @Nelmio\ApiDocBundle\Annotation\Operation()->path Using: \MyController->getMyActionOverride()
```
Logger::warning('Multiple definitions for ' . $identity . '->' . $property . "\n     Using: " . $context1 . "\n  Skipping: " . $context2);
```

Are my expectations incorrect? Is there an alternate way to achieve this? I know this isn't an ideal routing scheme, but I can't change the API unfortunately. 

```
    /**
     * @Operation(
     *     operationId="my_action_override",
     *     tags={"Action"},
     *     summary="Get a thing override",
     *     @SWG\Response(
     *         response="200",
     *         description="Returned when successful"
     *     )
     * )
     *
     * @Route("/myaction", condition="request.query.has('override')", name="myaction_override")
     */
    public function getMyActionOverride()...

    /**
     * @Operation(
     *     operationId="my_action",
     *     tags={"Action"},
     *     summary="Get a thing",
     *     @SWG\Response(
     *         response="200",
     *         description="Returned when successful"
     *     )
     * )
     *
     * @Route("/myaction", name="myaction")
     */
    public function getMyAction()...
```

**Comment by GuilhemN** [comment] 2020-10-01 21:23
This issue was already reported in https://github.com/nelmio/NelmioApiDocBundle/issues/1693.

The problem is that OpenAPI does not allow having several operations under the same path, see https://swagger.io/docs/specification/2-0/paths-and-operations/:
> Swagger defines a unique operation as a combination of a path and an HTTP method. This means that two GET or two POST methods for the same path are not allowed – even if they have different parameters (parameters have no effect on uniqueness). 

In the version 4 of this bundle, the annotations of your two routes would be merged but I'm actually not sure this is any better than having an exception preventing possibly unexpected behavior.

**Comment by medzhidov** [comment] 2020-10-29 23:41
@GuilhemN, but what about the same path's but on different host?

This code throws error:
https://i.imgur.com/Cep6TNA.png
https://i.imgur.com/JK30lkN.png

**Comment by GuilhemN** [comment] 2020-11-01 10:48
The issue is the same, OpenApi does not support having different routes using the same path, even on different hosts.
Depending on what you're need is, creating an area for each host may solve your issue, see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html.

**Comment by chrisguitarguy** [comment] 2022-05-16 11:30
going to close this one as it's not something OpenAPI supports, and so we can't support it.

**Closed by chrisguitarguy** 2022-05-16 11:30 UTC
