### ISSUE TITLE
Symfony 4 don't load services.xml

### ISSUE THREAD

**Issue by za4me** [nelmio/NelmioApiDocBundle#1158] opened 2017-12-22 12:49 UTC
Hi i'm install this bundle and in `example.com/api/` url get `LogicException` with message `Controller not found: service "nelmio_api_doc.controller.swagger_ui" does not exist.`

I think symfony cannot load services.xml inside bundle, but why? Or i make something wrong?

**Comment by scaytrase** [comment] 2017-12-22 20:05
services are private by default now, so this controller should be explicitly marked as `public`

**Comment by GuilhemN** [comment] 2017-12-23 09:26
@scaytrase not sure what you mean, it is already explicitely made public.

**Comment by scaytrase** [comment] 2017-12-23 11:14
@GuilhemN hm, indeed

@za4me did you enabled bundle in kernel?

**Comment by dbu** [comment] 2017-12-23 11:21
duplicate of #1143 - there is no recipe for flex yet.

**Closed by dbu** 2017-12-23 11:21 UTC

**Comment by Gemorroj** [comment] 2018-01-03 17:52
any workaround?

**Comment by scaytrase** [comment] 2018-01-03 17:59
@Gemorroj not to use flex for this bundle?

**Comment by za4me** [comment] 2018-01-04 07:58
Hi guys. Sorry i'm later, but i remove all packages and install this and it working fine. I forgot the exact solution, but like last time, I did not add the code in `routing.yml`.

**Comment by dbu** [comment] 2018-01-04 08:47
will be fixed with https://github.com/symfony/recipes-contrib/pull/226

**Comment by za4me** [comment] 2018-01-04 13:29
@dbu Thank a lot, now i need fix my another bundle for using new nelmio :D

**Comment by kochen** [comment] 2018-01-22 08:25
The `swagger_ui` controller requires both `twig` & `symfony/asset` which are not mentioned in the doc and are not added by the flex recipe.

If those are missing, the service `nelmio_api_doc.controller.swagger_ui` will not be autowired and therefor won't be found (regardless of it being public).

**Comment by GuilhemN** [comment] 2018-01-22 09:21
> are not added by the flex recipe

This is not possible afaik. We mention it in the routing of the recipe though.

> which are not mentioned in the doc

Please submit a PR if you think it's lacking.
