### ISSUE TITLE
[3.0] Follow up on #1065 - non annotation definitions cause validation notices

### ISSUE THREAD

**Issue by discordier** [nelmio/NelmioApiDocBundle#1082] opened 2017-09-11 15:01 UTC
The fix for #1065 (PR #1073) correctly fixes the validation problems for annotation based definitions, however any custom definitions referenced from annotations are causing user notices like:
```
User Notice: $ref "#/definitions/Error" not found for @SWG\Schema()
```

In this example, I have defined the definition via configuration:
```
nelmio_api_doc:
    definitions:
      Error:
        type: object
        properties:
          code:
            type: string
            description: "Error code"
          message:
            type: string
            description: "Error reason"
        required:
          - code
          - message
```

Generated API information looks ok, only the validation screws up.

Same happens when adding anything via an own describer, the hereby defined definitions and models screw up the annotation validator.

I tried to compensate by hacking `SwaggerPhpDescriber` by passing the config and adding an analysis pass which adds the definitions from the root config:
```php
    private function getProcessors(): array
    {
        $processors = [
            new AddDefaults(),
            new ModelRegister($this->modelRegistry),
            function (Analysis $analysis) {
                 // Add responses from base config.
                foreach ($this->externalDoc['responses'] as $key => $response) {
                    $annotation = new SWG\Response(array_merge(['response' => $key], $response));
                    $analysis->addAnnotation($annotation, null);
                }
                // Add definitions from base config.
                foreach ($this->externalDoc['definitions'] as $key => $definition) {
                    if (isset($definition['properties'])) {
                        $definition['properties'] = array_map(function ($key, $prop) {
                            return new SWG\Property(array_merge(['property' => $key], $prop));
                        }, array_keys($definition['properties']), $definition['properties']);
                    }
                    $annotation = new SWG\Definition(array_merge(['definition' => $key], $definition));
                    $analysis->addAnnotation($annotation, null);
                }
            }
        ];

        return array_merge($processors, Analysis::processors());
    }
```
However, this only targets part of the problem (the things defined via configuration) and therefore we need a generic solution.

I am willing to to a PR as soon as we have decided on a route to go.

As I need it for a project, I'd rather get this fixed soon than downgrading any of the libraries.

**Comment by GuilhemN** [comment] 2017-09-13 21:14
Sorry I don't have much time these days so I can't search for a better solution than yours. Please do what you think is best :)

**Comment by GuilhemN** [comment] 2018-01-10 13:19
You can now also use `@Model` alongside `@Property` to avoid putting definitions in the config.

**Comment by discordier** [comment] 2018-01-30 18:29
While this is certainly possible, IMO we should also allow the other way around (having defined config and use it in application).
I am not a big fan of having ONLY annotation configuration and therefore I'd love to keep this issue open. Maybe we find some good solution sometime in the future.

**Comment by dbu** [comment] 2018-01-31 08:39
so the configuration is recognized and works, but triggers an incorrect warning? if so, that should indeed not be. @GuilhemN and i discussed about this in another issue, ideally we would have independant loaders that can individually be enabled or disabled that load route and model information from the various sources we have. validation for the most part should happen in a later step, when all sources have been aggregated. (however, this might make it super hard to fix real issues in a project, because the context can be lost when validating later...)

we both don't have the time atm to dig into this, but if you have time, please have a look and propose how you want to improve it so that we can discuss before you spend a lot of time refactoring.

**Comment by GuilhemN** [comment] 2018-01-31 18:49
@dbu in fact the issue is not the same here is, here it's zircote/swagger-php not knowing about our conf. 

A simple fix would be to remove reference validation (by not executing https://github.com/zircote/swagger-php/blob/master/src/Analysis.php#L293 in SwaggerPhpDescriber), I don't think it truly makes sense when using this bundle anyway.

**Comment by dbu** [comment] 2018-02-01 07:27
ah, so just swagger-php itself does a validation too early? do we validate ourselves in the end as well?

**Comment by GuilhemN** [comment] 2018-02-01 12:16
> ah, so just swagger-php itself does a validation too early?

Yes

> do we validate ourselves in the end as well?

No, we don't, but it could be a great addition.

**Comment by dbu** [comment] 2018-02-01 12:47
then question is if we would be ok to remove just this validation without having added validation of our own. missing validation would mean that errors go undetected, which is sneaky and hard to debug... building all that validation is probably quite some effort. i guess it would mean a validator on the models defined in `exsyst/swagger` - or does such a thing already exist? plus maybe a "strict" mode that would keep the individual validation, to use when the global validation fails and you don't know why.

**Comment by dbu** [comment] 2018-02-05 07:20
>> plus maybe a "strict" mode that would keep the individual validation, to use when the global validation fails and you don't know why.
>
> Not sure about this, it pushes bad practices imo.

my worry is that with a global validation, we can not pinpoint the problem to specific lines of code. but lets cross that bridge when we get there.

**Comment by GuilhemN** [comment] 2018-02-20 09:08
#1232 is merged and fixes your issue :)
After all I kept references validation, it wasn't that complicated.

**Closed by GuilhemN** 2018-02-20 09:08 UTC
