### ISSUE TITLE
Impossible to describe hashmap field in Entity

### ISSUE THREAD

**Issue by petr-buchin** [nelmio/NelmioApiDocBundle#1229] opened 2018-02-14 16:54 UTC
I have a `Media` and `MediaInfo` objects.
`Media` (image or video) has field `sizes` - a hash/dictionary, which key is an alias for the media size, and value is a `MediaInfo` instance. In JSON it may look like follows:
```json
{
    "original": {
        "url": "http://example.com/my-image.jpg",
        "width": 2000,
        "height": 2000
    },
    "small": {
        "url": "http://example.com/my-resized-image.jpg",
        "width": 100,
        "height": 100
    }
}
```
I use the `@Model` annotation in controller to display Media object.
I defined PHP docblock annotation for this `sizes` field as follows:

```php
    /**
     * @var MediaInfo[]
     */
    private $sizes = [];
```

But documentation displays `$sizes` field as a list.
So I decided to add Swagger annotation to that field for it to be displayed correctly in documentation:

```php
/**
     * @var MediaInfo[]
     * @Groups({"rest"})
     * @SWG\Property(
     *     type="object",
     *     @SWG\Property(property="original", ref="#/definitions/MediaInfo")
     *     @SWG\Property(property="small", ref="#/definitions/MediaInfo")
     *     @SWG\Property(property="medium", ref="#/definitions/MediaInfo")
     *     @SWG\Property(property="large", ref="#/definitions/MediaInfo")
     * )
     */
    private $sizes = [];
```

But this leads to an error:
![Error](https://i.imgur.com/1mL9Qyx.png).

So I googled and found this: https://github.com/nelmio/NelmioApiDocBundle/issues/1227#issuecomment-365579884.

Therefore I tried to use `@Model` annotation like so:

```php
/**
     * @var MediaInfo[]
     * @Groups({"rest"})
     * @SWG\Property(
     *     type="object",
     *     @SWG\Property(property="original", @Model(type=MediaInfo::class, groups={"rest"})),
     *     @SWG\Property(property="small", @Model(type=MediaInfo::class, groups={"rest"})),
     *     @SWG\Property(property="medium", @Model(type=MediaInfo::class, groups={"rest"})),
     *     @SWG\Property(property="large", @Model(type=MediaInfo::class, groups={"rest"}))
     * )
     */
    private $sizes = [];
```

...and got another error:
![Error](https://i.imgur.com/sp2UCk6.png)

So the question is: how do I describe a hashmap/dictionary/associative array entity field of the form `{string: object}` using this bundle, if it does not support definitions, and does not support `@Model` annotations anywhere but in controller?

**Comment by GuilhemN** [comment] 2018-02-14 17:57
Unfortunately, `@Model` does not mix well with `@Property`. You can eventually define manually your `MediaType` model in your config and use a reference like you did at first.

**Comment by petr-buchin** [comment] 2018-02-14 21:08
Thanks, I'll try!

**Comment by GuilhemN** [comment] 2018-02-14 21:57
Under `nelmio_api_doc.documentation.definitions`, see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#using-the-bundle.

**Comment by petr-buchin** [comment] 2018-02-14 22:00
@GuilhemN thank you very much!

**Comment by GuilhemN** [comment] 2018-02-14 22:04
You're welcome :) 

We need to find a solution to support `@Property` properly... Btw `@Model` is not supported at all when `@Property` is used inside a model (ie not inside a controller).

**Comment by petr-buchin** [comment] 2018-02-20 22:57
@GuilhemN could you please explain more little bit more in detail, what is the problem with `@Property` ? I would like to understand that, dive into that and help to find or implement a solution.

**Comment by GuilhemN** [comment] 2018-02-21 10:11
See https://github.com/nelmio/NelmioApiDocBundle/issues/1164#issue-284918467. The issue is that a ``@Model`` in a ``@Property`` annotation is always considered as an array because ``@Model`` works like ``@Schema``, when nested it is transformed in an ``@Items`` annotation.

**Comment by petr-buchin** [comment] 2018-02-28 13:43
@GuilhemN here is my opinion:
`@Model` annotation is about convenience. It should give user the possibility to describe his models without using Swagger annotations.
But the truth is this annotation rather makes this all more difficult. 
`@Model` annotation is really unusable with such a big number of limitations.

Why don't you want to start from allowing users to use `@SWG\Definition` annotation on their models? `@Definition` annotation is not about convenience. It's about the fact that this bundle is rather totally unusable without this annotation support.
If I cannot use `@Definition` annotation and must describe all my models via YAML to be able to describe my API - why would I use this bundle? 

What are you think about adding support for `@Definition` ?

**Comment by dbu** [comment] 2018-02-28 14:24
i think there is some misunderstanding here. the models can be described with annotations, one of the extractors is reading the normal php docblocks, and so on. 

@GuilhemN sounds like we need an entry in the FAQ explaining why model exists and why SWG\Definition is not supported ;-)

**Comment by petr-buchin** [comment] 2018-02-28 14:32
@dbu actually, model **cannot** be described via annotations. For example, I can use `@SWG\Property` in model to describe it's property, but that makes no sense, if I cannot refer to my model class. For example, I cannot refer to model from other model (because `@Model` works only in controllers) - I must describe my model as definition in config, and refer to that definition. Therefore, describing my model via annotations without ability to have a definition from this class makes no sense at all.
Also I cannot use `@Model` in property and have an object instead of array (https://github.com/nelmio/NelmioApiDocBundle/issues/1080). 

For now `@Model` annotation has no real use cases and is totally unusable.
And without `@Definition` annotation this bundle also becomes unusable :(

**Comment by GuilhemN** [comment] 2018-02-28 14:53
> Why don't you want to start from allowing users to use ``@SWG\Definition`` annotation on their models? ``@Definition`` annotation is not about convenience. It's rather about the fact that this bundle is totally unusable without this annotation support. 

Supporting `@Definition` would force us to parse all the files of the project and I don't want to go on this path while `@Model` does a better job imo.

> For example, I cannot refer to model from other model (because @Model works only in controllers)

Well this is just because no one took the time to implement it. It shouldn't be very complicated, it just requires some motivation and time. Note that most of the time, using `@var` and type hints is enough.

> Also I cannot use `@Model` in property and have an object instead of array (#1080).

This one's true, I guess https://github.com/nelmio/NelmioApiDocBundle/issues/1164#issuecomment-358239964 solution is acceptable to improve DX...

> @GuilhemN sounds like we need an entry in the FAQ explaining why model exists and why SWG\Definition is not supported ;-) 

Indeed, mostly because `@Model` is integrated with symfony (and fulfills `@Definition` role), and because supporting `@Definition` would force us to parse the whole project which is definitelly a bad practice.
`@Model` is not good enough for some uses right now (when using associative arrays, though they can be documented by using fake objects) but we should fix it rather than throwing it :)

**Comment by petr-buchin** [comment] 2018-02-28 15:14
> This one's true, I guess #1164 (comment) solution is acceptable to improve DX...
This solution does not work: for array of models documentation shows the model structure, but for one model it only shows empty object. 

> and because supporting @Definition would force us to parse the whole project which is definitelly a bad practice.

Well, parsing the whole project is what Symfony does itself to support autowiring and autoconfiguration. 
Also, I believe that when you are using Symfony Serializer's annotations, the whole project gets parsed (otherwise Symfony would need to parse file at runtime, which is not Symfony way and is a really bad practice). 

> @Model is not good enough for some uses right now
I'd rather say that it is really unusable.

> but we should fix it rather than throwing it :)
From what I know for now - there is already a lot of problems with this annotation, and no one can tell that this is the only problems with `@Model` approach :)

**Comment by GuilhemN** [comment] 2018-03-24 09:02
Most `@Model` drawbacks were fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1261.

> I'd rather say that it is really unusable. 

You're exagerating, associative arrays of objects are quite uncommon (if not bad practice?) and for other uses you can use type hints, definitions in config etc.

> Well, parsing the whole project is what Symfony does itself to support autowiring.
Also, I believe that when you are using Symfony Serializer's annotations, the whole project gets parsed (otherwise Symfony would need to parse file at runtime, which is not how Symfony works, and which is a really bad practice).

Not exactly, symfony parses a files subset choosen (in config) by the user. And about symfony serializer annotations, they're parsed at runtime, they're just cached.

**Closed** 2018-03-24 09:03 UTC
