### ISSUE TITLE
Nested definitions

### ISSUE THREAD

**Issue by dbu** [nelmio/NelmioApiDocBundle#1306] opened 2018-04-24 11:52 UTC
i think i found a bug with definitions handling - but i am not entirely sure if its caused by this bundle or by swagger php itself:

i have a model with one of the fields being another model. when the nested model is returned by one of my controllers, the doc is valid. but when the nested model is only ever mentioned inside the parent model, the definition of the child is not included in the json, crashing swagger-ui. where is the decision which definitions to include in the output?

**Comment by dbu** [comment] 2018-04-24 12:00
just realized that if i put a definition into the nelmio_api_doc.documentation.definitions section, it is included in the output. but its not detected from within the model. although the outer model is correctly converted and contains the reference to my inner model. is there a recursive layer missing somewhere?

**Comment by GuilhemN** [comment] 2018-04-25 17:54
I have no idea where this is coming from. I'll try to reproduce it and understand it this week-end. Probably somehow, a wrong model registry is used somewhere.

**Comment by aequasi** [comment] 2018-10-10 06:38
I think i'm able to reproduce it.

I have the following:

* Entities:
	* User
	* Invoice

`User` has `Invoices` (OneToMany, Doctrine ArrayCollection)

* Controllers:
	* UserController
		* getAction

This generates the spec correctly for user:

```
        "invoices": {
          "items": {
            "$ref": {
              "type": "App\\Entity\\Invoice"
            }
          },
          "type": "array"
        },
```

But, the reference definition is never created.

**Comment by goetas** [comment] 2018-10-10 06:42
@aequasi Any chance to send a failing test case?

**Comment by aequasi** [comment] 2018-10-10 06:47
Yeah, i can give it a try tomorrow

**Comment by aequasi** [comment] 2018-10-10 06:48
I could create a demo project as well, if that would help

**Comment by goetas** [comment] 2018-10-10 06:50
having a testcase in this repo would be better, but a demo project could be a valid alternative

**Comment by chrisguitarguy** [comment] 2022-03-26 20:28
GOing to close this due to lack of details or failing test case or reproducers.

This bit, though:

```
"$ref": {
              "type": "App\\Entity\\Invoice"
            }
```

Probably means an invalid use of `@Model`?

**Closed by chrisguitarguy** 2022-03-26 20:28 UTC
