### ISSUE TITLE
Migration from 2.x to 3.x

### ISSUE THREAD

**Issue by pesseyjulien** [nelmio/NelmioApiDocBundle#1019] opened 2017-06-21 15:15 UTC
Hi,

Thanks for the migration procedure but I'm getting the following error :

`You have requested a non-existent service "nelmio_api_doc.extractor.api_doc_extractor"`

**Comment by GuilhemN** [comment] 2017-06-21 15:18
Hi,
You need to execute the command before upgrading the bundle constraint, did you do that ?

**Comment by pesseyjulien** [comment] 2017-06-21 15:19
I'm getting this error while executing the command yes. Sorry, I forgot to mention that !

**Comment by GuilhemN** [comment] 2017-06-21 15:30
Ok, but to execute your command you need the 2.x version of the bundle, you have to upgrade to 3.0 only *after* executing it. Were you using NelmioApiDocBundle 2.x (check your `composer.json` file) when executing the command ?

**Comment by pesseyjulien** [comment] 2017-06-21 15:48
I see, thanks !

**Comment by reneszabo** [comment] 2017-06-21 22:14
Hi, love this bundle btw. 
have 2 questions, is the integrations with swagger gonna support the input=formType ?
and also got an error updating to beta.
![image](https://user-images.githubusercontent.com/434504/27409060-81b65526-56ad-11e7-9765-24a1a19eb66d.png)

**Comment by GuilhemN** [comment] 2017-06-22 19:16
Thanks :)

>  have 2 questions, is the integrations with swagger gonna support the input=formType ?

That's related to https://github.com/nelmio/NelmioApiDocBundle/issues/956, we need someone enough motivated to make it but I'd like to have it for sure!

> dunno if relates to the bundle thow. Just gonna leave it there...

At first sight, I don't see how this could be related to the bundle maybe try running the command with `-vvv` to have more infos?

I'm closing this as the issue is solved ;)

**Closed by GuilhemN** 2017-06-22 19:16 UTC

**Comment by Marwen238** [comment] 2019-04-11 09:00
Hi,
I execute the command before upgrading the bundle constraint but i have the same issue `You have requested a non-existent service "nelmio_api_doc.extractor.api_doc extractor".`

**Comment by GuilhemN** [comment] 2019-04-11 12:09
Is the bundle activated? What version is installed?

If that's not enough to solve your issue, could you provide us a reproducer please?

**Comment by Marwen238** [comment] 2019-04-11 12:41
Yes the bundle is activated and i use the version 3.3 of nalmio

**Comment by GuilhemN** [comment] 2019-04-11 18:24
Ok, please refer to https://github.com/nelmio/NelmioApiDocBundle/issues/1019#issuecomment-310116193, this command only works when using 2.x :)
