### ISSUE TITLE
[BUG] 🐛 `Multiple @OA\MediaType() with the same mediaType="application/json"` after `composer update -W`

### ISSUE THREAD

**Issue by DavidGarciaCat** [nelmio/NelmioApiDocBundle#2209] opened 2024-01-31 18:37 UTC
The Swagger UI page was generated as expected, but it failed with the title's error message after upgrading Composer dependencies:

```
User Warning: Multiple @OA\MediaType() with the same mediaType="application/json":
    \App\Controller\...\CreateUserController->__invoke()
    \App\Controller\...\CreateUserController->__invoke()
    in /opt/project/src/Controller/.../CreateUserController.php
```

```
composer update -W
```

```
Package operations: 0 installs, 58 updates, 0 removals
  - ...
  - Upgrading zircote/swagger-php (4.8.2 => 4.8.3): Extracting archive
  - Upgrading phpstan/phpdoc-parser (1.24.5 => 1.25.0): Extracting archive
  - Upgrading phpdocumentor/type-resolver (1.7.3 => 1.8.0): Extracting archive
  - Upgrading nelmio/api-doc-bundle (v4.13.0 => v4.19.2)
  - ...
```

Any suggestions?

**Comment by DavidGarciaCat** [comment] 2024-01-31 18:40
Installing the specific `4.17.*` version via composer, it seems to solve the problem:

```
{
    ...
    "require": {
        ...
        "nelmio/api-doc-bundle": "4.17.*",
        ...
    },
    ...
}
```

**Comment by DjordyKoert** [comment] 2024-01-31 18:44
Could you share how your `CreateUserController` `__invoke` method looks? I assume you are using Symfony's `MapRequestPayload` attribute there, which I think is causing the issue.

**Comment by DavidGarciaCat** [comment] 2024-02-06 12:27
Hey, @DjordyKoert,

I wondered if the attributes I added in my last comment were helpful. I'm not pushing or rushing for an update (in the end, this is an open-source repo), but it would be nice to get an update, if any, or in case I could provide more details.

Thanks,

**Comment by DjordyKoert** [comment] 2024-02-06 12:36
Hey @DavidGarciaCat sorry for not responding 😅 

The information you provided is plenty because I am pretty sure that the issue is caused because of the `#[MapRequestPayload]` attribute which Nelmio attempts to describe for you.

I think the quick-fix on your end could be to remove the usage `#[OA\RequestBody]` attribute  (or remove the `content:` param in case you still want to provide a description or something similair for you request body) because. It will still generate a valid api documentation for you endpoint which includes the request body for your endpoint.

**Comment by DavidGarciaCat** [comment] 2024-02-06 12:39
Thanks for the quick response, @DjordyKoert,

If I understood you correctly, this would be a temporary fix to upgrade the bundle and keep rendering the documentation. Still, another minor/patch release will be necessary to fix the exception - am I right here?

Once again, thanks for the quick response.

**Comment by DjordyKoert** [comment] 2024-02-06 12:42
Yes correct. I will try and find some time somewhere soon to see if I can fix this. If I manage to fix this then a patch will be released for this most likely.

**Comment by DavidGarciaCat** [comment] 2024-02-06 12:51
Much appreciated for the update - enjoy the rest of your week!

**Closed** 2024-02-07 13:21 UTC

**Comment by DjordyKoert** [comment] 2024-02-07 13:23
Good news, I managed to fix it in https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.19.3 😄

**Comment by DavidGarciaCat** [comment] 2024-02-08 18:58
Thanks for the update, @DjordyKoert - Enjoy the rest of your week!
