### ISSUE TITLE
`Multiple @OA\Response() with the same response` since 4.9.0

### ISSUE THREAD

**Issue by javer** [nelmio/NelmioApiDocBundle#1993] opened 2022-05-04 08:13 UTC
After updating `nelmio/api-doc-bundle` from `4.8.2` to `4.9.0` we encounter the following exception:
```
User Warning: Multiple @OA\Response() with the same response="200":
\ApiController->action() in src/Controller/ApiController.php on line 94
\ApiController->action() in src/Controller/ApiController.php on line 94
```
for the following controller:
```php
<?php

namespace App\Controller;

use Nelmio\ApiDocBundle\Annotation as ApiDoc;
use OpenApi\Attributes as OA;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/api')]
class ApiController
{
    #[Route(path: '/action')]
    #[ApiDoc\Operation(['tags' => ['Version 1.0'], 'summary' => 'Do action'])]
    #[OA\Response(response: '200', description: 'OK')]
    public function action()
    {
    }
}
```
The issue was introduced (according to `git bisect`) in this commit: https://github.com/nelmio/NelmioApiDocBundle/commit/2295f68b89138e04c8b9685d6161c0a976c8288d

The small project-reproducer can be found here: https://github.com/javer/zircote-swagger-php-issue-1220

See original issue https://github.com/zircote/swagger-php/issues/1220, my comment with all details https://github.com/zircote/swagger-php/issues/1220#issuecomment-1116296866 and further investigation https://github.com/zircote/swagger-php/issues/1220#issuecomment-1116895871

**Comment by Slashhh-es** [comment] 2022-05-11 08:44
Having the same issue

**Comment by GuilhemN** [comment] 2022-06-06 15:42
Thank you for this very detailed issue and for the investigation, I think it is now quite clear what's causing this and I will try to come up with a fix ASAP.

**Comment by copiri-six** [comment] 2022-06-14 21:43
If it helps, I have just asked a related question at the `swagger-php` repo, [here](https://github.com/zircote/swagger-php/issues/1261).  I think part of it is still their issue, but the viewing portion may be caused by this bug.  Mentioning it in case that use case helps fully test the solution.  Thanks!

**Comment by GuilhemN** [comment] 2022-07-02 05:49
This will be fixed in next release of zircote/swagger-php thanks to https://github.com/zircote/swagger-php/pull/1279.
Closing as fixed.

Thanks for the report! And sorry for the delay.

**Closed by GuilhemN** 2022-07-02 05:49 UTC
