### ISSUE TITLE
I have all routes twice in the documentation

### ISSUE THREAD

**Issue by TheKassaK** [nelmio/NelmioApiDocBundle#431] opened 2014-07-07 12:40 UTC
I have a controller Apicontroller.php with somes routes, like : 

/**
	 * @Get("/login/{username}/{password}")
	 * @ApiDoc(
     *  description="User Loggin",
     *  resource=true,
     *  parameters={
     *      {"name"="username", "dataType"="string", "required"=true, "description"="Username"},
     *      {"name"="password", "dataType"="string", "required"=true, "description"="Password"},
     *  }
     * )
	*/
	public function loginAction($username, $password){

       }

But, i have in my routing.yml prefix all my routes by /api.

So, when i check the documentation i have for exemple : 
/api/login/{username}/{password} AND /login/{username}/{password}

I just want the route with /api.. How can i do that ?

**Comment by willdurand** [comment] 2015-05-16 11:47
duplicate of #309

**Closed by willdurand** 2015-05-16 11:47 UTC
