### ISSUE TITLE
http issue

### ISSUE THREAD

**Issue by yaroslav-yozma-tech** [nelmio/NelmioApiDocBundle#1850] opened 2021-07-16 09:44 UTC
I use Symfony 5 and NelmioApiDocBundle 4.x, i got this error on my remote server(at my local all works fine)
`VM1438:1 Mixed Content: The page at 'https://domain.com/api/doc' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain.com/_wdt/352787'. This request has been blocked; the content must be served over HTTPS.`

I suppose it caused by bad configuration. Any solution?

**Comment by GuilhemN** [comment] 2021-07-16 10:02
This is most likely not related to this bundle.

I think `_wdt/*` routes correspond to the Symfony profiler. It may be related to https://github.com/symfony/symfony/issues/37980, the issue may be caused by running symfony behind a nginx proxy not passing the https scheme header for instance.

**Comment by GuilhemN** [comment] 2021-07-18 16:58
I suppose this fixed your issue then, so I'm closing it. Feel free to reopen if that's not the case ;)

**Closed by GuilhemN** 2021-07-18 16:58 UTC
