### ISSUE TITLE
Calling var_dump or similar anywhere in code cause "failed to fetch error"

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1516] opened 2019-05-13 13:42 UTC
tried with:
+ `var_dump`
+ `var_export`
+ `print_r`
+ `echo`

Note: This is happening only from the browser api doc sandbox, not with rest clients

**Comment by GuilhemN** [comment] 2019-05-17 09:59
What version of the bundle are you using?

**Comment by florianajir** [comment] 2019-05-17 10:01
currently installed v3.4.0

**Comment by GuilhemN** [comment] 2019-05-17 10:44
Swagger-ui is a third-party library so it's harder for me to debug it.

Does https://github.com/nelmio/NelmioApiDocBundle/pull/1518 fix your issue by any luck?
In case not, folks on symfony's slack would likely know swagger-ui better than I do, sending a message there might help.
Or if you could provide a reproducer but i'm not sure i'll have enough time to investigate soon unfortunately

**Comment by chrisguitarguy** [comment] 2022-04-01 20:39
Closing due to age, but I'd expect any extra output to break JSON stuff.

**Closed by chrisguitarguy** 2022-04-01 20:39 UTC
