### ISSUE TITLE
[dev-master] Response model array no example

### ISSUE THREAD

**Issue by charliefancelli** [nelmio/NelmioApiDocBundle#1684] opened 2020-07-20 14:36 UTC
Hi, 

When we describe 
```
@OA\Response(
     *         response="200",
     *         description="Returned when successful",
     *         @OA\JsonContent(
     *              @OA\Schema(
     *                  type="array",
     *                  @OA\Items(ref=@Model(type=User::class, groups={"full"}))
     *              )
     *         )
     *     ),
```
No example and Schema are available

--

If we remove the array all is works (but i need an array :) )

```
@OA\Response(
     *         response="200",
     *         description="Returned when successful",
     *         @Model(type=User::class, groups={"full"})
     *     ),
```

**Comment by GuilhemN** [comment] 2020-07-20 15:20
The issue is that `@OA\JsonContent` behaves as a `@OA\Schema` (see https://github.com/zircote/swagger-php/blob/26c9e75fdec48aa07ed7d6dc255ad2fa10250ece/Examples/swagger-spec/petstore-simple/SimplePetsController.php#L37-L40 for instance), so you should use instead:
```
     *     @OA\Response(
     *         response="200",
     *         description="Returned when successful",
     *         @OA\JsonContent(
     *              type="array",
     *              @OA\Items(ref=@Model(type=User::class, groups={"full"}))
     *         )
     *     ),
```

**Comment by charliefancelli** [comment] 2020-07-20 16:11
thank for your reply, it's working ;)

i think there is a mistake in the Symfony documentation => https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html#using-the-bundle

```
@OA\Response(
     *     response=200,
     *     description="Returns the rewards of an user",
     *     @OA\JsonContent(
     *        @OA\Schema(
     *             type="array",
     *             @OA\Items(ref=@Model(type=Reward::class, groups={"full"}))
     *        )
     *     )
     * )
````
Regards,

**Comment by GuilhemN** [comment] 2020-07-20 18:13
Indeed, thanks for the report :)
I fixed it in https://github.com/nelmio/NelmioApiDocBundle/commit/a82a1c141605f581d033c531311013635cc53a9c.

**Comment by GuilhemN** [comment] 2020-07-24 06:22
I'm closing this as the original issue is fixed.

**Closed** 2020-07-24 06:21 UTC
