### ISSUE TITLE
Incompatibility with DoctrineBundle v2.8

### ISSUE THREAD

**Issue by webinarium** [nelmio/NelmioApiDocBundle#2064] opened 2022-12-31 00:07 UTC
Hi,

When I upgraded the `doctrine/doctrine-bundle` from 2.7 to 2.8, the **NelmioApiDocBundle** stopped to work:
```
    The service "nelmio_api_doc.model_describers.object" has a dependency on a
    non-existent service "annotations.reader".
```

Looks like the `doctrine/doctrine-bundle` moved their dependency on `doctrine/annotations` from the `required` to `require-dev` section, starting from version 2.8.0.

Any advice, workaround, or maybe a new version of this great bundle which will work with the recent **DoctrineBundle**, please? :)

P.S. The **NelmioApiDocBundle** is great, btw. Thanks!

**Comment by reksc** [comment] 2023-01-04 16:44
I have the same issue, but for other reason. This is the only package from my dependencies, that forces the download of v1 branch of `doctrine/annotations` and this has other side-effects. And, yeah, NelmioApiDocBundle is great :).

**Comment by GuilhemN** [comment] 2023-01-04 17:27
> P.S. The NelmioApiDocBundle is great, btw. Thanks!

Thank you ❤️ 

> When I upgraded the doctrine/doctrine-bundle from 2.7 to 2.8, the NelmioApiDocBundle stopped to work:

I don't really understand the root cause here, `zircote/swagger-php` still has a header dependency on `doctrine/annotations` so it should still work fine.

Which version of NelmioApiDocBundle are you using? Is it v3.x?
Are you activating annotations in your framework bundle config? (i.e. `framework.annotations: true`)

If not too sensitive, having your composer.lock (maybe without the private packages if you use any) could help pinpoint the root issue.

> I have the same issue, but for other reason. This is the only package from my dependencies, that forces the download of v1 branch of doctrine/annotations and this has other side-effects. And, yeah, NelmioApiDocBundle is great :).

Unfortunately that's a hard dependency as we use the annotations from `zircote/swagger-php` as models. Unless they remove the dependency here it would be a too big investment to remote this dependency here.

**Comment by DerManoMann** [comment] 2023-01-04 19:37
swagger-php [4.5.4](https://github.com/zircote/swagger-php/releases/tag/4.5.4) adds support for doctrine/annotations ^2.0 - should that help?

**Comment by webinarium** [comment] 2023-01-04 22:11
Thank you for responding! Answering your questions:
- I'm using the most recent version of NelmioApiDocBundle - 4.10.2
- no, I'm not activating annotations in the framework bundle config; should I?

I played a little, trying to generate a demo project with as less dependencies as possible, and got some new information. So, what I have done:

1. Created a new Symfony project (v6.2.4) using Symfony CLI
```
symfony new demo-2064
cd demo-2064
```

2. Added required minimum of dependencies:
```
composer require doctrine/orm
composer require doctrine/doctrine-bundle:2.7.2
composer require nelmio/api-doc-bundle --dev
```

Please note I'm adding **NelmioApiDocBundle** as a dev-dependency.

3. Updated the `composer.json`, so **DoctrineBundle** points to `^2.7` and then:
```
composer update --lock
```

The resulted project works fine, you can download it (including `composer.lock`) from [here](https://github.com/webinarium/demo-2064/releases/tag/v0.1.0) and run `composer install` successfully.

4. Then, I upgraded the **DoctrineBundle** to most recent v2.8.0:
```
composer update doctrine/doctrine-bundle
```

This fails with the error message I reported before. The only file changed is `composer.lock`, where `doctrine/annotations` was moved from the `packages` section to `packages-dev` one (since new **DoctrineBundle** version moved it to the dev-dependencies, too).

You can download this from [here](https://github.com/webinarium/demo-2064/releases/tag/v0.2.0) and run `composer install` to see the error.

5. After that, I added `doctrine/annotations` to the project as another dependency:
```
composer require doctrine/annotations
```

Obviously, this moved the `doctrine/annotations` back to the `packages` section in `composer.lock`, so the project is fine again now. You can download this from [here](https://github.com/webinarium/demo-2064/releases/tag/v0.2.1).

If I repeat all the steps above, but with installing **NelmioApiDocBundle** normally (without `--dev` flag), then there is no issue at all. So, I'm a bit confused now - does it all work as expected, and I just screwed up with my project dependencies? Or should it actually work even in my not-so-popular case where I install the bundle as a dev-dep? Because the annotations package is still in the dev-deps section, right? Though, I may be missing something.

Sorry for the longread, hopefully it helps and won't be a waste of your time reading it. :)

Just in case, my environment:
```
PHP 8.1.2
Composer 2.4.4
Symfony CLI 5.4.20
PopOS 22.04
```

**Comment by GuilhemN** [comment] 2023-01-04 22:46
Thanks for the additional details.
I think the root cause is that you use NelmioApiDocBundle as a dev dependency, Symfony core moves and more to enabling features by default only if they are available in prod (the `willBeAvailable` field in https://github.com/symfony/symfony/blob/c301d9a49a1562b39d8c28eee2b5f4791d51ab14/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L971 checks that).

An immediate solution for you is to add `framework.annotations: true` to your dev config.

Longer term I see either:
- modify the nelmio recipe and add a file `packages/dev/nelmio.yaml` enabling the annotations
- configure the annotations reader manually in NelmioApiDocBundle 

I prefer just modifying the recipe personally although that's possibly bothering for people also using NelmioApiDocBundle as a dev dependency and that will have the same issue (because of doctrine-bundle or another dependency) until they upgrade to the new recipe...

**Comment by webinarium** [comment] 2023-01-05 00:07
I think upgrading the recipe is a fine solution. Meanwhile, those who use **NelmioApiDocBundle** as a dev dependency can update `framework.annotations` until new version is released.

Thank you for your help!

**Comment by GuilhemN** [comment] 2023-02-03 17:16
Thinking of it again, not sure what to do here. 
The recipe is not meant to be used when NelmioApiDocBundle is installed for dev only (you need to move the nelmio config in the dev folder to have it work when your app doesn't install dev dependencies, right?).

So in any case this will require manual steps on your side, and I'd say adding the `framework.annotations: true` config is one of these steps.

**Comment by webinarium** [comment] 2023-02-03 21:31
Well, actually, I really did move the nelmio config to the dev folder, so I think you are right - it's ok to do an extra step of enabling annotations manually. Probably, there is no changes required in the library. I raised the issue to ask for the help and got it for sure! I don't mind if you just close it now. :)

Thank you for your support!

**Comment by DerManoMann** [comment] 2023-12-07 00:38
`doctrine/annotations` will be optional soon in swagger-php: https://github.com/zircote/swagger-php/pull/1508

**Comment by tarlepp** [comment] 2024-01-02 15:39
Any news with this issue?

**Comment by DjordyKoert** [comment] 2024-01-02 15:42
@tarlepp an update of NelmioApiDocBundle should be enough to fix this. https://github.com/nelmio/NelmioApiDocBundle/pull/2164 has made the `doctrine/annotations` optional.

**Comment by tarlepp** [comment] 2024-01-02 15:49
@DjordyKoert Oh, I see that there is multiple new releases today - I'll try to upgrade that bundle and see what happens - thanks!

**Comment by tarlepp** [comment] 2024-01-02 16:02
@DjordyKoert I can confirm that upgrading NelmioApiDocBundle to latest version solves this issue - big thanks for quick reply!

**Comment by DjordyKoert** [comment] 2024-01-02 16:03
Glad to hear that @tarlepp! I will go ahead and close this issue :)

**Closed by DjordyKoert** 2024-01-02 16:03 UTC

**Comment by DoobleD** [comment] 2024-01-02 19:42
The latest version solved it for me as well, thank you!
